backend/.gitignore, backend/src/main/resources/application-prod.properties, backend/src/test/java/com/woowacourse/zzimkkong/ZzimkkongApplicationTests.java
=> feat: 자동배포 shell script 추가 및 테스트 프로필 설정 (#30)

frontend/package.json
- version 수정
- package name 수정
- main 수정
close #32
=> chore: package.json 수정(#32)

backend/src/main/java/com/woowacourse/zzimkkong/WebConfig.java
CORS 이슈 해결
현재 모든 origin에서 접속 가능
프론트서버 올라오면 수정할 것
Close #42
=> fix: CORS 이슈 해결 (#42)

frontend/package.json, frontend/src/App.tsx, frontend/src/api/api.ts, frontend/src/api/join.ts, frontend/src/constants/message.ts, frontend/src/hooks/useInput.ts, frontend/src/pages/Join/Join.tsx, frontend/yarn.lock
- 이메일 입력 후 blur 시 이메일 중복확인 API 요청을 보냄.
-  결과에 따라 Input 창 하단에 메세지를 보여줌.
close #22
=> feat: 회원가입시 이메일 중복확인 기능 (#22)

backend/build.gradle, backend/gradle/wrapper/gradle-wrapper.properties, backend/src/docs/asciidoc/index.adoc, backend/src/docs/asciidoc/member.adoc, backend/src/main/resources/application-local.properties, backend/src/main/resources/static/docs/index.html, backend/src/test/java/com/woowacourse/zzimkkong/controller/DocumentUtils.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/MemberControllerTest.java
- application-local.properties 설정을 update로 수정했습니다!
=> feat: restdocs를 이용한 api 문서화 (#28)

backend/src/test/java/com/woowacourse/zzimkkong/controller/MemberControllerTest.java
=> fix: MemberControllerTest 중복 메서드 삭제

backend/src/docs/asciidoc/member.adoc, backend/src/main/resources/application-local.properties, backend/src/main/resources/application-prod.properties, backend/src/main/resources/static/docs/index.html, backend/src/test/java/com/woowacourse/zzimkkong/controller/AcceptanceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/AuthControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/MemberControllerTest.java
- 이메일 중복확인 성공에 대한 테스트 작성
- 로그인 API RestDocs 적용
=> feat: 누락 테스트 추가 및 추가된 API RestDocs 적용 (#52)

backend/src/main/java/com/woowacourse/zzimkkong/ZzimkkongApplication.java
KST
Co-authored-by: sakjung <ssangyu123@gmail.com>
=> fix: timezone KST로 변경 (#63)

backend/src/main/java/com/woowacourse/zzimkkong/controller/ControllerAdvice.java
- ControllerAdivce에 logger 추가
- 모든 예외에 대해 `error`가 아닌 `warn`으로 통일했습니다.
- DataAccessException과 InvalidFormatException은 예외메시지를 아래와 같이 넣어주었습니다.
- DataAccessException : "예상치 못한 문제가 발생했습니다. 개발자에게 문의하세요."
- InvalidFormatException : "날짜 및 시간 데이터 형식이 올바르지 않습니다."
Close #71
=> feat: exception 발생 시 logger 작성 (#71)

backend/src/main/java/com/woowacourse/zzimkkong/domain/Reservation.java
=> fix: 종료시간 일치 시 예약 추가되는 오류 수정 (#83)

backend/src/main/java/com/woowacourse/zzimkkong/domain/Reservation.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/ReservationControllerTest.java
=> fix: 이미 예약이 존재하는 시간에 예약추가 시 성공하는 문제 (#83)

backend/src/main/java/com/woowacourse/zzimkkong/ZzimkkongApplication.java
=> fix: application timezone 세팅 변경

frontend/src/constants/message.ts, frontend/src/constants/regexp.ts, frontend/src/pages/Join/Join.tsx
-  회원가입시 조직명 유효성 검사 후 메세지를 표시하는 기능
- 1자 이상, 특수문자 일부 허용(- , _ , !, ?, ., , ]) 검증하는 정규식
```js
const regexp = /^[a-zA-Z0-9ㄱ-ㅎ가-힣ㅏ-ㅣ-_!?.,\s]{1,}$/;
regexp.test('+') // false
regexp.test('찜 꽁 ! ?') // true
```
Close #105
=> feat: 회원가입시 조직명 유효성 검사 후 메세지를 표시하는 기능

frontend/src/api/api.ts
=> feat: api baseURL 변경

backend/src/main/java/com/woowacourse/zzimkkong/WebConfig.java
- proxy 서버에게만 resource sharing이 가능하도록 설정
- 이게 머지 안하고는 테스트가 안되네... 혹시나 배포되고 동작 제대로 안 할수도 있으니까 이슈는 안닫을게
=> feat: CORS 설정 프록시 서버만 허용하도록 변경한다.

backend/src/main/java/com/woowacourse/zzimkkong/WebConfig.java
- 모든 origin으로 부터 들어오는 요청을 허용한다
- 죄송합니다. 발표내용에 맞게 설정 완료하려고 설정했는데 정정하겠습니다
=> feat: CORS - 모든 origin으로 부터의 요청을 허용한다.

backend/src/main/java/com/woowacourse/zzimkkong/WebConfig.java
- CORS 모든 origin으로 부터의 요청을 허용한다.
- 죄송할 따름입니다. 반성하겠습니다
=> feat: CORS 모든 origin으로 부터의 요청을 허용한다.

frontend/src/App.tsx, frontend/src/assets/svg/luther.svg, frontend/src/components/Button/Button.stories.tsx, frontend/src/components/Button/Button.styles.ts, frontend/src/components/Button/Button.tsx, frontend/src/components/DateInput/DateInput.stories.tsx, frontend/src/components/DateInput/DateInput.styles.ts, frontend/src/components/DateInput/DateInput.tsx, frontend/src/components/Panel/Panel.stories.tsx, frontend/src/components/Panel/Panel.styles.ts, frontend/src/components/Panel/Panel.tsx, frontend/src/components/Panel/PanelHeader.stories.tsx, frontend/src/components/Panel/PanelHeader.styles.ts, frontend/src/components/PinRadio/PinRadio.stories.tsx, frontend/src/components/PinRadio/PinRadio.styles.ts, frontend/src/components/PinRadio/PinRadio.tsx, frontend/src/components/ReservationListItem/ReservationListItem.styles.ts, frontend/src/constants/path.ts, frontend/src/pages/ProviderReservationList/ProviderReservationList.styles.ts, frontend/src/pages/ProviderReservationList/ProviderReservationList.tsx, frontend/src/pages/UserMain/UserMain.styles.ts, frontend/src/pages/UserMain/UserMain.tsx, frontend/src/types/common.ts
공간 더미데이터는 임시로 아래처럼 구성했습니다.
```javascript
{
id: 1,
spaceName: '백엔드 강의실',
textPosition: 'bottom',
color: '#FED7D9',
coordinate: {
x: 100,
y: 90,
},
}
```
|Property|Description|Type|Default|
|------|---|---|---|
|`text`|화면에 표시될 RadioPin의 이름|`string`||
|`textPosition`|`text`를 Pin 이미지 기준 어느 방향에 표시할지 여부|`'left' \| 'right' \| 'top' \| 'bottom'`|`'bottom'`|
|`coordinate`|컴포넌트가 표시될 좌표|`x: number`<br>`y: number`||
|`color`|핀 이미지의 색상|`string?`||
|`name`|`<input type="radio" neme="여기 들어갈 값">`|`string`||
- Button 컴포넌트의 variant에 'text' 속성 추가
- Panel 컴포넌트에 기본 Padding을 제거하고 Panel.Inner 컴포넌트 추가
- ReservationListItem의 align-items 스타일 제거
- RadioPin의 크기가 적당한지 봐주세요!
- 페이지 주소(path)를 한 번 정리할 필요가 있는 것 같습니다.
- 공간관리자와 예약자의 영문명을 통일하면 좋겠습니다.
- provider, user로 고정인가요???
Close #9
Close #13
=> feat: 예약자 main페이지 UI 구현

backend/src/main/java/com/woowacourse/zzimkkong/dto/space/SpaceFindResponse.java
- Space에 Color, TextPosition, Coordinate 값이 추가되었기 떄문에 이를 반영합니다.
close #116
=> feat: 공간 정보에 textPosition, color, coordinate를 같이 응답

frontend/package.json, frontend/public/manifest.json, frontend/webpack.config.js, frontend/yarn.lock
=> feat: manifest.json 추가

backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java
- 예약시간에 대한 검증을 KST 시간 기준으로 하도록 수정했습니다.
- 정상적으로 동작하는지 확인 후 이슈 닫겠습니다.
Close #
=> fix: 예약시간에 대한 검증을 KST 기준으로 하도록 변경

backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java, backend/src/test/java/com/woowacourse/zzimkkong/service/GuestReservationServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/ManagerReservationServiceTest.java
- local time만 KST로 수정했습니다.
- 정상 동작 확인 후 이슈 닫겠습니다.
Close #이슈번호
=> fix: 예약시간 검증 시 local time만 KST로 수정

backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java, backend/src/test/java/com/woowacourse/zzimkkong/service/GuestReservationServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/ManagerReservationServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/ServiceTestFixture.java
- timezone offset 상수화
- 버그 정상동작 확인했으니 이슈 닫겠습니다~
Close #221
=> refactor: timezone offset 상수화

backend/src/main/java/com/woowacourse/zzimkkong/DataLoader.java, backend/src/main/java/com/woowacourse/zzimkkong/controller/MapController.java, backend/src/main/java/com/woowacourse/zzimkkong/domain/Map.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/map/MapCreateRequest.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/map/MapCreateResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/infrastructure/AuthorizationExtractor.java, backend/src/main/java/com/woowacourse/zzimkkong/service/MapService.java, backend/src/test/java/com/woowacourse/zzimkkong/CommonFixture.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/AuthControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/ManagerReservationControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/MapControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/MapServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/ServiceTestFixture.java
- 공간 관리자의 맵 생성 API를 구현하였습니다.
- svg 데이터를 어떻게 처리할지 논의해보아야합니다.
Co-authored-by: @dusdn1702 
Co-authored-by: @tributetothemoon 
Close #164
=> feat: 공간 관리자는 맵을 생성할 수 있다.

backend/src/main/resources/application-prod.properties
- ddl auto 설정을 none으로 변경했습니다.
Close #225
=> build: ddl auto 설정을 none으로 변경

frontend/.storybook/main.js, frontend/webpack.config.js
- svgr에서 viewBox를 표시하지 않는 기본 설정을 변경
Close #230
=> refactor: webpack svgr viewBox 설정

frontend/src/components/DateInput/DateInput.styles.ts, frontend/src/components/Drawer/Drawer.styles.ts, frontend/src/components/Header/Header.styles.ts, frontend/src/components/Modal/Modal.styles.ts, frontend/src/constants/style.ts
Co-authored-by: JO YUN HO <yujo.dev@gmail.com>
Co-authored-by: Shim MunSeong <puterism.k@gmail.com>
Close #217
=> refactor: z-index 상수화

backend/src/main/resources/application-prod.properties
=> build: ddl auto 설정을 create으로 변경

backend/src/docs/asciidoc/index.adoc
- 추가되지 않은 map api 문서를 추가합니다.
Close #247
=> doc: 추가된 API에 대한 문서를 작성한다.

backend/src/main/java/com/woowacourse/zzimkkong/domain/Map.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/map/MapFindResponse.java, backend/src/main/resources/application-prod.properties, backend/src/test/java/com/woowacourse/zzimkkong/CommonFixture.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/AcceptanceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/MapControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/MapServiceTest.java
- ddl auto 설정을 create으로 변경했습니다.
- Map entity 중 mapImage의 이름을 mapImageUrl로 변경했습니다.
- Map entity 중 mapDrawingData 와 mapImageUrl의 타입을 Lob으로 변경했습니다.
- 테스트 CommonFixture 중 mapDrawingData 와 mapImageUrl의 더미데이터를 구체화했습니다.
- 정상동작 확인 후 이슈 닫겠습니다.
Close #이슈번호
=> refactor: Map entity를 수정한다.

backend/src/main/java/com/woowacourse/zzimkkong/infrastructure/BatikConverter.java, backend/src/main/resources/application-local.properties, backend/src/main/resources/application-prod.properties, backend/src/main/resources/application-test.properties, backend/src/test/java/com/woowacourse/zzimkkong/infrastructure/BatikConverterTest.java
=> Fix: 운영환경에서 svg -> png 변경이 안 되는 문제 해결

.github/workflows/frontend-test.yml, frontend/package.json
- 프론트엔드 테스트를 실행하는 workflow 작성
- `jest --watch` 명령어로 테스트 실행 시, 무한루프에 걸려 `scripts`를 추가 했습니다.
- `"test:ci": "jest"` 
- 아래는 전체 workflow 파일입니다. 주속으로 역할을 적었습니다.
```yml
name: CI # 전체 파일의 이름
on: [push, pull_request] # 트리거 되는 동작 
jobs: # 실행할 동작
build: # 빌드하기 위한 환경
name: Test
runs-on: ubuntu-latest
env:
working-directory: ./frontend
strategy: 
matrix:
node-version: [14.16.x]
steps: # 실제 실행하는 동작
- uses: actions/checkout@v2
- name: Node Version ${{ matrix.node-version }}
uses: actions/setup-node@v1
with:
node-version: ${{ matrix.node-version }}
- name: yarn install
run: yarn install
working-directory: ${{ env.working-directory }}
- name: yarn test
run: yarn test:ci
working-directory: ${{ env.working-directory }}
```
Close #260
=> chore: 프론트엔드 테스트를 실행하는 workflow 작성

frontend/src/api/api.ts, frontend/src/api/map.ts, frontend/src/components/Button/Button.styles.ts, frontend/src/components/Button/Button.tsx, frontend/src/components/IconButton/IconButton.styles.ts, frontend/src/components/IconButton/IconButton.tsx, frontend/src/components/Panel/PanelHeader.styles.ts, frontend/src/components/Panel/PanelHeader.tsx, frontend/src/components/PinRadio/PinRadio.styles.ts, frontend/src/components/PinRadio/PinRadio.tsx, frontend/src/constants/editor.ts, frontend/src/constants/path.ts, frontend/src/constants/routes.tsx, frontend/src/pages/ManagerMapCreate/ManagerMapCreate.styles.ts, frontend/src/pages/ManagerMapCreate/ManagerMapCreate.tsx, frontend/src/types/common.ts, frontend/src/types/editor.ts, frontend/src/types/styled.d.ts, frontend/src/utils/style.ts
- 맵 편집 페이지 UI 구현
- 맵 생성 기능 추가
- 기타 추가할 내용이 있다면 추가합니다.
- 없는 경우 삭제
Close #174 
Close #176
=> feat: map 편집 페이지

backend/src/main/java/com/woowacourse/zzimkkong/WebConfig.java
- header에서 반환해주는 location으로 JS에서 바로 참조할 수 있도록 허용합니다.
Close #285
=> fix: location header 관련 cors 이슈 해결

backend/build.gradle, backend/src/main/resources/application-local.properties, backend/src/main/resources/application-prod.properties, backend/src/main/resources/application-test.properties, backend/src/main/resources/db.migration/prod/V1_init.sql
- db flyway를 적용했습니다.
- flyway가 적용이 되면  entity에 변경사항이 생길 때마다 sql문을 같이 작성해주셔야 합니다.
- 작성 위치와 작성 방법은 [위키](https://github.com/woowacourse-teams/2021-zzimkkong/wiki/%5BBE%5D-DB-flyway#flyway-%EC%A0%81%EC%9A%A9-%ED%9B%84-db-%EB%B3%80%EA%B2%BD%EB%B0%A9%EB%B2%95)에 작성해두었으니 참고해주세요.
- 버전관리에 유의해주세요.. 
Close #253
=> feat: db flyway를 적용한다.

backend/src/main/java/com/woowacourse/zzimkkong/dto/space/SpaceCreateUpdateRequest.java, backend/src/main/java/com/woowacourse/zzimkkong/service/SpaceService.java, backend/src/main/resources/db/migration/prod/V4__change_enabled_day.sql, backend/src/test/java/com/woowacourse/zzimkkong/controller/SpaceControllerTest.java
flyway에 V4_change_enabled_name.sql 추가, 
spaceCreateUpdateRequestDto spaceName -> name 수정
Close #333
=> fix: db flyway sql문 추가, space dto 이름 변경

frontend/src/api/api.ts, frontend/src/pages/ManagerMain/ManagerMain.tsx, frontend/yarn.lock
- 다른 페이지로 이동할 수 있다.
<!DOCTYPE html><figure class="md-table-fig" cid="n6" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">
  | …
=> refactor: 토큰이 유효하지 않을 경우 Redirection 하는 로직을 axios에서 실행하도록 변경

backend/src/main/resources/db/migration/prod/V6__preset_column_change.sql
- database preset manager_id -> member_id로 변경했습니다.
Close #363
=> fix: database preset column명 수정

backend/src/main/java/com/woowacourse/zzimkkong/domain/Reservation.java
- Lombok 적용 과정에서 해당 로직이 삭제되어 다시 생성합니다.
미처 살피지 못해 죄송합니다😭🙏
Close #373
=> refactor: Reservation 생성시 초 이하 단위를 자른다.

backend/src/main/java/com/woowacourse/zzimkkong/service/SpaceService.java, backend/src/test/java/com/woowacourse/zzimkkong/service/SpaceServiceTest.java
- space service save 함수에 한줄이 빠져있어 추가했습니다.
Close #388
=> fix: space 생성 시 s3에 업로드 안되는 문제를 해결합니다.

backend/src/main/java/com/woowacourse/zzimkkong/WebConfig.java
- allowedOriginPattern 관련 설정을 제거했습니다.
Close #398
=> fix: CORS originpattern 설정 제거

frontend/src/pages/ManagerMain/ManagerMain.tsx
=> fix: 맵이 없어도 공유링크가 클립보드에 복사되는 문제

frontend/src/pages/GuestMap/GuestMap.styles.ts, frontend/src/pages/GuestMap/GuestMap.tsx, frontend/src/pages/GuestReservation/GuestReservation.styles.ts, frontend/src/pages/GuestReservation/GuestReservation.tsx, frontend/src/pages/GuestReservationEdit/GuestReservationEdit.styles.ts, frontend/src/pages/GuestReservationEdit/GuestReservationEdit.tsx, frontend/src/utils/datetime.ts
- 예약자 메인 페이지 예약 목록 UI 수정 구현
- 예약자 예약 페이지에서 예약 조건 내에서 입력할 수 있도록 폼을 설정한다.
Close #402
=> feat: 예약자 메인 페이지 예약 목록 UI 수정 구현

backend/build.gradle, backend/src/main/java/com/woowacourse/zzimkkong/SecurityConfig.java, backend/src/main/java/com/woowacourse/zzimkkong/domain/Member.java, backend/src/main/java/com/woowacourse/zzimkkong/service/AuthService.java, backend/src/main/java/com/woowacourse/zzimkkong/service/MemberService.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/AcceptanceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/GuestReservationControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/GuestSpaceControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/ManagerReservationControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/ManagerSpaceControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/MapControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/MemberControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/domain/MemberTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/AuthServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/ServiceTest.java
- 회원가입시 비밀번호를 암호화합니다.
Close #421
=> 회원 비밀번호를 암호화한다.

backend/src/main/resources/db/migration/prod/V8__password_alter.sql
=> feat: db 서버 분리

frontend/src/api/api.ts, frontend/src/constants/api.ts
- 개발 환경 서버로 API 요청되도록 주소를 변경했습니다.
Close #470
=> chore: 개발 환경 서버로 API 요청되도록 주소 변경

backend/src/main/java/com/woowacourse/zzimkkong/StorageConfig.java, backend/src/main/java/com/woowacourse/zzimkkong/config/AuthenticationPrincipalConfig.java, backend/src/main/java/com/woowacourse/zzimkkong/config/SecurityConfig.java, backend/src/main/java/com/woowacourse/zzimkkong/config/SlackConfig.java, backend/src/main/java/com/woowacourse/zzimkkong/config/StorageConfig.java, backend/src/main/java/com/woowacourse/zzimkkong/config/WebConfig.java
- 개발 서버에서 이미지 버켓 업로드에 실패하는 문제를 해결합니다.
Close #475
=> fix: dev 프로파일로 서버 운영시 이미지 업로드에 실패하는 문제 해결

frontend/jest.config.js, frontend/src/__mocks__/handlers.ts, frontend/src/__mocks__/mockData.ts, frontend/src/__mocks__/setupTest.ts, frontend/src/__tests__/reservation.test.tsx, frontend/src/components/ReservationListItem/ReservationListItem.tsx, frontend/src/constants/message.ts, frontend/src/pages/GuestMap/GuestMap.tsx, frontend/src/pages/GuestReservation/GuestReservation.tsx, frontend/src/types/response.ts
=> test: 예약 CRUD 테스트 코드를 작성한다.

backend/src/main/java/com/woowacourse/zzimkkong/dto/ValidatorMessage.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/member/PresetCreateRequest.java, backend/src/test/java/com/woowacourse/zzimkkong/dto/PresetCreateRequestTest.java
- 프리셋 이름에 공백을 허용하도록 regex를 수정했습니다.
Close #483
=> feat: 프리셋 이름에 공백 허용하도록 regex 수정

frontend/src/constants/api.ts
- 개발 환경에서의 API의 BASE_URL 변경
Close #486
=> chore: 개발 환경에서의 API의 BASE_URL 변경

backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java
- 젠킨스 파이프라인으로 옮기는 작업을 하고 있는데 촉발 커밋이 필요해서 코드 냄새 없애면서 같이 진행하겠습니다.
- 이슈는 모든 job에 대해 변경 작업 완료된 후 닫겠습니다.
=> refactor: 코드 냄새 제거 (젠킨스 촉발)

backend/src/main/java/com/woowacourse/zzimkkong/repository/MapRepository.java, backend/src/main/java/com/woowacourse/zzimkkong/repository/PresetRepository.java, backend/src/main/java/com/woowacourse/zzimkkong/repository/SpaceRepository.java, backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java
- 젠킨스 파이프라인으로 옮기는 작업을 하고 있는데 촉발 커밋이 필요해서 코드 냄새 없애면서 같이 진행하겠습니다.
- 이슈는 모든 job에 대해 변경 작업 완료된 후 닫겠습니다.
=> refactor: 코드 냄새 제거(젠킨스 촉발)

backend/src/main/java/com/woowacourse/zzimkkong/ZzimkkongApplication.java, backend/src/main/java/com/woowacourse/zzimkkong/service/strategy/ExcludeReservationCreateStrategy.java
- front dev 용 파이프라인이 제대로 동작하는지 확인합니다
=> feat: front dev 젠킨스 파이프라인을 생성한다

backend/src/main/java/com/woowacourse/zzimkkong/ZzimkkongApplication.java
- 젠킨스 파이프라인으로 옮기는 작업을 하고 있는데 촉발 커밋이 필요해서 코드 냄새 없애면서 같이 진행하겠습니다.
- 이슈는 모든 job에 대해 변경 작업 완료된 후 닫겠습니다.
=> refactor: 필요없는 주석 제거 (젠킨스 촉발)

backend/src/main/resources/application-dev.properties
- dev properties에 connection pool size와 timeout 설정을 추가했습니다.
- prod properties는 서브모듈 문제로 oAuth 이슈가 끝난 다음 추가하도록 하겠습니다.
- 이슈는 prod properties까지 반영한 뒤 닫겠습니다.
=> build: connection 관련 dev 설정 추가

backend/src/main/resources/db/migration/prod/V9__oauth.sql
- oauth 관련 칼럼 추가된 oauth_provider varchar(10) 칼럼을 추가했습니다.
- oauth 관련 변경된 password 칼럼을 nullable=true로 변경했습니다.
Close #540
=> fix: flyway oauth 관련 칼럼 추가 및 변경

frontend/src/api/guestReservation.ts, frontend/src/api/join.ts, frontend/src/api/login.ts, frontend/src/api/managerReservation.ts, frontend/src/constants/message.ts, frontend/src/constants/throwError.ts, frontend/src/hooks/useFormContext.ts, frontend/src/pages/ManagerSpaceEditor/units/Preset.tsx, frontend/src/utils/localStorage.ts
=> refactor:  api URL 변경 및 개발자 메세지와 유저 메세지 분리

backend/src/main/resources/application-dev.properties
- dev properties에 jpa 타임존 설정을 추가했습니다.
- prod properties는 replication 이슈와 함께 반영하겠습니다.
Close #556
=> fix: dev properties timezone issue 해결하도록  설정 변경

frontend/.gitignore, frontend/package.json, frontend/src/App.tsx, frontend/src/__tests__/reservation.test.tsx, frontend/src/constants/message.ts, frontend/src/constants/path.ts, frontend/src/constants/routes.tsx, frontend/src/pages/GuestMap/GuestMap.styles.ts, frontend/src/pages/GuestMap/GuestMap.tsx, frontend/src/pages/GuestMap/units/ReservationDrawer.styles.ts, frontend/src/pages/GuestMap/units/ReservationDrawer.tsx, frontend/src/pages/GuestReservation/GuestReservation.tsx, frontend/src/test-utils.tsx, frontend/tsconfig.json, frontend/webpack.config.js, frontend/yarn.lock
Co-authored-by: Sunny K <sunnyk5780@gmail.com>
Co-authored-by: Shim MunSeong <puterism.k@gmail.com>
- Test가 실패하는 문제가 있어 `test-utils` 파일에 `Suspense`를 추가했습니다. d406ac8
- 저희가 이번에 적용한 `BundleAnalyzerPlugin` 떄문에 젠킨스에서 build가 끝나지 않고 무한루프 도는 현상이 있었습니다.
- `BundleAnalyzerPlugin`의 `analyzerMode` 옵션을 설정하여 production일 때는 분석 파일이 static하게 생성되도록 하였습니다. 899dc2d
```js
new BundleAnalyzerPlugin({
analyzerMode: isDevelopment ? 'server' : 'static',
}),
```
Close #552
=> refactor: Code Spliting 및 Dynamic Import 적용

frontend/src/pages/ManagerSpaceEditor/providers/SpaceFormProvider.tsx, frontend/src/pages/ManagerSpaceEditor/units/Preset.tsx
=> fix: 프리셋이 설정된 상태에서 다른 공간 선택 시 프리셋이 초기화되지 않는 문제

frontend/src/constants/path.ts
- OAuth 로그인 시 Redirect URI이 제대로 설정되지 않는 문제 수
머지 후 동작 확인이 필요합니다!
Close #565
=> fix: OAuth 로그인 시 Redirect URI이 제대로 설정되지 않는 문제 수정

frontend/src/api/login.ts, frontend/src/pages/ManagerLogin/ManagerLogin.tsx
- 토큰 만료 후 Header에 로그아웃 버튼이 표시되는 문제 수정
- 이번에 버그를 고치면서 `useEffect` 안에서 `useMutation`을 사용해보려다가 아무리 해도 안 돼서 찾아보니 React-query의 `useMutation`이 이미 `useEffect`를 사용하고 있어서 안 되는거였더라구요...ㅎㅎ
- 알고 있으면 좋을거 같아서 공유합니다!
- [`useMutation` 구현부 링크](https://github.com/tannerlinsley/react-query/blob/ee7ca0bf1e813fd727f25abeb67755f43b636b3f/src/react/useMutation.ts)
Close #503
=> fix: 토큰 만료 후 Header에 로그아웃 버튼이 표시되는 문제 수정

frontend/src/pages/ManagerMain/ManagerMain.styles.ts, frontend/src/pages/ManagerMain/ManagerMain.tsx, frontend/src/pages/ManagerMain/units/MapDrawer.styles.ts, frontend/src/pages/ManagerMain/units/MapDrawer.tsx, frontend/src/pages/ManagerMain/units/ReservationList.styles.ts, frontend/src/pages/ManagerMain/units/ReservationList.tsx
=> refactor: ManagerMain 페이지 리팩터링

backend/src/main/java/com/woowacourse/zzimkkong/config/LogAspectConfig.java, backend/src/main/java/com/woowacourse/zzimkkong/config/logaspect/LogAspect.java, backend/src/main/java/com/woowacourse/zzimkkong/config/logaspect/LogAspectConfigurer.java
- 변수명 및 클래스명이 다소 일관성이 없는 문제가 있었습니다. 특히 `LogRegistry` 같은 경우 중복되는 문제까지 있어, 이를 수정했습니다.
Close #739
=> feat: LogAspect 관련 클래스명 및 변수명 수정

.gitmodules, backend/build.gradle, backend/src/main/resources/appenders/logstash-appender-dev.xml, backend/src/main/resources/appenders/logstash-appender-prod.xml, backend/src/main/resources/logback-spring.xml
- ElasticSearch, Logstash, Kibana, Kafka를 제거합니다.
- infra-appender 서브모듈 역시 제거되었습니다.
Close #751
=> refactor: ElasticSearch, Logstash, Kibana, Kafka 삭제

backend/src/main/java/com/woowacourse/zzimkkong/service/MapService.java, backend/src/test/java/com/woowacourse/zzimkkong/domain/MapTest.java
- map 수정 시 thumbnail 안되는 문제 해결
Close #768
=> fix: map 수정 시 thumbnail 안되는 문제 해결

backend/src/main/resources/application-dev.properties
- 포트번호를 분리해서 개발용 환경을 세팅했습니다.
- db는 같은 인스턴스에 있는 애를 쓰는데 database 이름을 구분했습니다.
- 운영용 : zzimkkong
- 개발용 : zzimkkong_dev
Close #770
=> chore: 개발용 환경 세팅

backend/src/main/java/com/woowacourse/zzimkkong/service/SpaceService.java
- 공간 CUD API에서 맵의 썸네일을 업데이트합니다.
Close #784
=> fix: 공간 CUD API에서 맵의 썸네일을 업데이트하도록 수정

frontend/src/pages/ManagerMain/ManagerMain.tsx
- 공지사항 및 슬랙 URL 설정 후 창이 바로 닫히도록 수정합니다.
Close #828
=> fix: 공지사항 및 슬랙 URL 설정 후 창이 바로 닫히도록 수정

backend/src/main/java/com/woowacourse/zzimkkong/domain/TimeUnit.java, backend/src/main/resources/db/migration/prod/V17__drop_unused_column.sql, backend/src/main/resources/db/migration/prod/V17__preset_drop_column_enable.sql
- 칼럼 드롭 flyway 작성
- 시간 단위 사용자 친화적으로 보여주도록 수정
- 그냥 유조 개발하면서 발견하는 디펙 처리 이 PR에 같이 태워도 될듯?...
- FE 머지하면서 이것도 같이 머지
=> feat: preset table - reservation_enable 컬럼 제거

frontend/package.json
=> chore: version 1.5.0

backend/src/main/resources/logback-spring.xml
- 프로파일(prod, dev, local)에 따라 로그가 다른 경로에 저장되도록 수정합니다
```
~/logs/$profile/'yyyy-mm-dd'/$log_level
```
Close #853
=> feat: 프로파일에 따라 로그가 다른 경로에 저장되도록 수정

backend/src/main/java/com/woowacourse/zzimkkong/domain/EnabledDayOfWeek.java, backend/src/main/java/com/woowacourse/zzimkkong/domain/Setting.java
- setting 끼리 겹치는 지 검증 할 때 요일도 보도록 수정
Close #852
=> fix: setting 끼리 겹치는 지 검증 할 때 요일도 보도록 수정

frontend/src/pages/ManagerSpaceEditor/units/Form.styles.ts
=> hotfix: 1.5.0 - 2

frontend/package.json
=> hotfix: 1.5.1

frontend/package.json
=> chore: version 2.0.0

frontend/src/pages/GuestMap/GuestMap.styles.ts, frontend/src/pages/GuestMap/GuestMap.tsx, frontend/src/pages/GuestMap/providers/GuestMapFormProvider.tsx, frontend/src/pages/GuestMap/units/Aside.styled.tsx, frontend/src/pages/GuestMap/units/Aside.tsx, frontend/src/pages/GuestMap/units/ReservationForm.styled.ts, frontend/src/pages/GuestMap/units/ReservationForm.tsx, frontend/src/pages/GuestMap/units/ReservationList.styled.ts, frontend/src/pages/GuestMap/units/ReservationList.tsx
- 예약현황 조회 시, 공간을 선택할 수 있는 기능
- 모바일 화면에서 예약 화면이 깨지는 문제 수정
- 예약 가능 시간이 목록형으로 보여지도록 수정
=> feat: 예약현황 조회 시, 공간을 선택할 수 있는 기능

frontend/src/pages/GuestMap/GuestMap.styles.ts, frontend/src/pages/GuestMap/GuestMap.tsx, frontend/src/pages/GuestMap/providers/GuestMapFormProvider.tsx, frontend/src/pages/GuestMap/units/Aside.styled.tsx, frontend/src/pages/GuestMap/units/Aside.tsx, frontend/src/pages/GuestMap/units/ReservationForm.styled.ts, frontend/src/pages/GuestMap/units/ReservationForm.tsx, frontend/src/pages/GuestMap/units/ReservationList.styled.ts, frontend/src/pages/GuestMap/units/ReservationList.tsx
* feat: 예약현황 조회 시, 공간을 선택할 수 있는 기능
* fix: 모바일 화면에서 예약 화면이 깨지는 문제 수정
* fix: 예약 가능 시간이 목록형으로 보여지도록 수정
=> release: v2.0.0 

backend/src/main/java/com/woowacourse/zzimkkong/repository/ReservationRepository.java, backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java, frontend/src/hooks/infiniteQuery/useNonLoginReservations.ts, frontend/src/pages/GuestNonLoginReservationSearch/GuestNonLoginReservationSearch.tsx, frontend/src/pages/GuestNonLoginReservationSearch/units/GuestNonLoginReservationSearchResult.styles.ts, frontend/src/pages/GuestNonLoginReservationSearch/units/GuestNonLoginReservationSearchResult.tsx
- 지난 예약 조회 안됨 안내 메세지 문구 추가
- 검색 결과가 없을 시, 안내 메세지 출력
- BE 코드 수정 있는 거는 무시해주세요~
Close #908 #911
=> feat: 비회원 예약 조회 개선

backend/src/main/java/com/woowacourse/zzimkkong/dto/member/ProfileEmojiResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationInfiniteScrollResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationOwnerResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/space/SpaceFindAllAvailabilityResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/space/SpaceFindAvailabilityResponse.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/MemberControllerTest.java
=> fix: 비밀번호 변경 테스트 요청 url 오기입 수정

backend/src/docs/asciidoc/member.adoc
- 비밀번호 변경에 대한 API 문서를 추가합니다.
Close #909
=> feat: 비밀번호 변경 API 문서 추가

frontend/src/pages/GuestMap/units/GuestMapDrawing.styles.ts
- 논의할 내용을 적습니다.
- 학습한 내용, 공유할 내용 등을 적습니다.
- 위키에 작성했다면 링크 첨부, 없는 경우 삭제
- 기타 추가할 내용이 있다면 추가합니다.
- 없는 경우 삭제
Close #912
=> feat: 비활성화 상태를 좀 더 명확하게 구분하기

frontend/src/components/Loader/Loader.ts, frontend/src/pages/GuestNonLoginReservationSearch/GuestNonLoginReservationSearch.tsx, frontend/src/pages/GuestNonLoginReservationSearch/units/GuestNonLoginReservationSearchResult.styles.ts, frontend/src/pages/GuestNonLoginReservationSearch/units/GuestNonLoginReservationSearchResult.tsx
=> feat: 비회원 예약 조회 loader 추가

frontend/package.json
- frontend version up 2.0.0 -> 2.1.0
=> chore: front version up 2.0.0 -> 2.1.0

backend/src/main/java/com/woowacourse/zzimkkong/dto/member/MemberFindResponse.java
- 내 정보 조회시 oauth provider 정보 필드 추가
Close #934
=> feat: 내 정보 조회시 oauth provider 정보 필드 추가

backend/src/main/java/com/woowacourse/zzimkkong/service/SpaceService.java
- 예약 가능 공간 조회 시, 과거 시간 검증 하도록 수정
Close #938
=> fix: 예약 가능 공간 조회 시, 과거 시간 검증 하도록 수정

backend/src/main/java/com/woowacourse/zzimkkong/service/SpaceService.java
- [예약 가능 공간 조회 시, 과거 시간 검증 하도록 수정 #938
=> hotfix: v2.1.0

frontend/package.json
=> release: 2.1.1
