frontend/package.json, frontend/yarn.lock
- Windows 환경에서 `NODE_ENV`를 사용할 수 있도록 `cross-env` 패키지를 추가하고 적용함.
Close #39
=> chore: `cross-env` 패키지 추가 및 적용 (#39)

frontend/src/components/Panel/PanelContext.ts
- `PanelContext`의 타입이 맞지 않는 문제를 수정합니다.
- `PanelContext`의 value가 사용하는 타입을 생성하여 적용했습니다.
#56 에서 추가로 수정하는 과정에서 미처 발견하지 못하고 바로 머지를 해서 생긴 이슈입니다.
Close #76
=> fix: `PanelContext`의 타입이 맞지 않는 문제 수정 (#76)

frontend/src/api/join.ts, frontend/src/components/Input/Input.styles.ts, frontend/src/constants/message.ts, frontend/src/constants/regexp.ts, frontend/src/pages/Join/Join.tsx
- useQuery
- `async`요청을 통해 데이터를 변경하지 않을 때 사용
- `GET`
- useMutation
- `async`요청을 통해 데이터를 변경시킬 때 사용
- `POST`, `UPDATE`, `PUT` 등
- useQuery
```tsx
const isValidEmail = useQuery(['isValidEmail', email], getValidateEmail, {
enabled: false,
retry: false,
onSuccess: () => {
setEmailMessage(MESSAGE.JOIN.VALID_EMAIL);
},
onError: (error: AxiosError) => {
setEmailMessage(error?.response?.data.message);
},
});
```
- useMutation
```tsx
const mutation = useMutation(postJoin, {
onSuccess: () => {
alert(MESSAGE.JOIN.SUCCESS);
history.push(PATH.LOGIN);
},
onError: () => {
alert(MESSAGE.JOIN.FAILURE);
},
});
const handleSubmitJoinForm: FormEventHandler<HTMLFormElement> = (event) => {
event.preventDefault();
if (!email || !password || !passwordConfirm || !organization) return;
mutation.mutate({ email, …
```
=> feat: 공간관리자 회원가입 기능 구현 (#47)

backend/src/main/java/com/woowacourse/zzimkkong/ZzimkkongApplication.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationFindAllResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationFindResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationSpaceResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/member/NoSuchMemberException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/member/PasswordMismatchException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/reservation/NoSuchReservationException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/reservation/NonMatchingStartAndEndDateException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/reservation/ReservationPasswordException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/space/NoSuchSpaceException.java, backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java, backend/src/main/resources/application-local.properties, backend/src/test/java/com/woowacourse/zzimkkong/controller/ReservationControllerTest.java
- 예약자가 맵의 모든 공간에 대한 예약을 조회하면,
- spaceId 순서대로 먼저 정렬 후,
- startTime 순서대로 정렬해서 보여준다.
- 예약자가 맵의 특정 공간에 대한 예약을 조회하면 startTime 순서대로 정렬해서 보여준다.
- 공간의 정렬기준은 공간 생성 시 자동으로 생성되는 spaceId 즉, `공간 생성순`입니다.
- 예약의 정렬기준은 예약 시작시간 startTime 즉, `예약 빠른순`입니다.
Close #100
=> feat: 예약조회 시 시간순으로 정렬하는 로직 추가

frontend/src/App.styles.ts, frontend/src/api/login.ts, frontend/src/assets/svg/close.svg, frontend/src/components/Modal/Modal.stories.tsx, frontend/src/components/Modal/Modal.styles.ts, frontend/src/components/Modal/Modal.tsx, frontend/src/constants/palette.ts, frontend/src/types/styled.d.ts, frontend/src/utils/datetime.ts
- 현재 `hover`시 opacity를 줄이는 방법으로 Style을 줬는데 `hover`시 나타내는 방법을 통일하면 좋을거 같습니다.
| prop            | Type      | Description                                                  |
| --------------- | --------- | ------------------------------------------------------------ |
| `open`          | boolean   | true: Modal이 열림.<br />false: Modal이 닫힘.                |
| dimmed          | boolean   | true: dimmed영역 클릭시 Modal이 닫힌다.<br />false: dimmed영역 클릭시 Modal이 닫히지 않는다. |
| showCloseButton | boolean   | true: close button이 보인다.<br />false: close button이 보이지 않는다. |
| children        | ReactNode | Children                                                     |
- 수정/삭제 Modal
- 비밀번호 입력 Modal
- CloseButton Modal
Close #95
=> feat: Modal 컴포넌트 구현

frontend/src/components/Button/Button.stories.tsx, frontend/src/components/Button/Button.styles.ts
- background - primary[400] -> primary[100]
---
- text: black[400] -> gray[400]
- border: black[400] -> gray[400]
Close #108
=> feat: Button 컴포넌트가 disabled 됐을 때 색을 변경하는 기능

backend/src/main/java/com/woowacourse/zzimkkong/controller/ReservationController.java, backend/src/main/java/com/woowacourse/zzimkkong/domain/Space.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationSpaceResponse.java
- 특정 맵에 대한 전체 예약을 조회할 때 공간별로 분류되어 예약이 조회되는데, 이 때 공간의 Id값만 응답되고 있었습니다.
- 이 때 공간의 이름도 같이 제공합니다.
- ReservatonController 메소드의 순서가 헷갈려 다시 정렬해보았습니다. 문제가 없을까 싶습니다~
Close #109
=> feat: 맵(Map)에 대한 예약 조회시 공간(Space)의 이름도 같이 응답 

backend/src/docs/asciidoc/member.adoc, backend/src/main/java/com/woowacourse/zzimkkong/AuthenticationPrincipalConfig.java, backend/src/main/java/com/woowacourse/zzimkkong/controller/AuthController.java, backend/src/main/java/com/woowacourse/zzimkkong/controller/ControllerAdvice.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/AuthControllerTest.java
- 토큰 유효성 검증하는 API를 구현한다.
- WebConfig와 AuthenticationPrincipalConfig가 모두 WebConfigurer를 구현하는 것이 싫어서 AuthenticationPrincipalConfig가 WebConfig를 상속하도록 했습니다. 어떤가요?
- 김김의 구현에서 LoginInterceptor와 JwtUtil이 모두 Bean으로 등록되어 있어서 Config에서 두 의존성을 주입받아야 했는데 이 부분은 어떤가요?
Close #118
=> feat: 토큰 유효성 검증 API를 구현한다.

frontend/src/api/reservation.ts, frontend/src/components/Input/Input.styles.ts, frontend/src/components/Input/Input.tsx, frontend/src/components/ReservationListItem/ReservationListItem.stories.tsx, frontend/src/components/ReservationListItem/ReservationListItem.tsx, frontend/src/constants/message.ts, frontend/src/constants/regexp.ts, frontend/src/hooks/useReservations.ts, frontend/src/pages/UserReservation/UserReservation.styles.ts, frontend/src/pages/UserReservation/UserReservation.tsx, frontend/src/types/common.ts, frontend/src/types/response.ts
- 예약자가 공간을 예약할 수 있는 기능 및 API 연동
- `Input` 컴포넌트의 `message` prop이 nullish일 때, 메시지 영역만큼의 여백이 생기지 않도록 수정
- `mapId`가 1이고 `spaceId`가 1인 경우에 한정하여 예약이 가능하도록 기능을 구현했습니다. 추후 공간을 선택하는 페이지가 구현되었을 때, 별도의 PR에서 추가 수정할 예정입니다.
Close #27
Close #99
=> feat: 예약자가 공간을 예약할 수 있는 기능 구현 및 API 연동

backend/src/main/java/com/woowacourse/zzimkkong/controller/ControllerAdvice.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/ErrorResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/member/MemberSaveResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/member/TokenResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationCreateResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationFindAllResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationFindResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationSpaceResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/slack/Attachment.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/slack/Attachments.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/slack/SlackResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/service/AuthService.java, backend/src/main/java/com/woowacourse/zzimkkong/service/MemberService.java, backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/ReservationControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/MemberServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/ReservationServiceTest.java
- 인자가 한 개인 정적팩토리 메서드명을 from으로 수정했습니다.
- 정적 팩토리 메서드를 사용할 때 인자가 한 개이면 `from`, 여러 개이면 `of`를 사용하는 것으로 통일하겠습니다.
- 정적 팩토리 메서드의 **인자에도 final 붙이는 것**으로 통일하겠습니다.
- 불가피한 경우를 제외하고 정적팩토리 메서드는 **객체를 인자로 받아 메서드 내부에서 getter를 사용하는 것**으로 통일하겠습니다.
Close #135
=> refactor: DTO 정적팩토리 메서드 형식 통일

frontend/src/constants/reservation.ts, frontend/src/pages/UserReservation/UserReservation.tsx
- 이름은 최대 20자까지만 입력할 수 있도록 수정
- `maxlength` 적용
- 사용 목적은 최대 100자까지만 입력할 수 있도록 수정
- `maxlength` 적용
- 비밀번호 입력 시 4자까지만 입력할 수 있도록 수정하고, 모바일에서 숫자 키보드가 먼저 보이도록 수정
- `minlength`, `maxlength`, `inputmode="numeric"` 적용
Close #133
=> fix: 예약자 예약 페이지 입력 폼에 최대 입력 길이 및 기타 폼 설정 추가

frontend/webpack.config.js
- 중복되는 'resolve' 옵션
- mode 옵션
- devServer open 옵션
```js
module.exports = () => {
const isDevelopment = process.env.NODE_ENV !== 'production';
return {
mode: isDevelopment ? 'development' : 'production', // <-- new 🌟
devServer: {
port: 3000,
open: true, // <-- new 🌟
hot: true,
historyApiFallback: true,
},
...
};
```
Close #141
=> chore: webpack 중복되는 설정 제거 및 mode 설정 추가

frontend/src/App.styles.ts, frontend/src/api/space.ts, frontend/src/components/DateInput/DateInput.styles.ts, frontend/src/components/DateInput/DateInput.tsx, frontend/src/components/Panel/Panel.styles.ts, frontend/src/components/Panel/PanelHeader.styles.ts, frontend/src/components/PinRadio/PinRadio.tsx, frontend/src/hooks/useInput.ts, frontend/src/hooks/useSpaces.ts, frontend/src/pages/UserMain/UserMain.styles.ts, frontend/src/pages/UserMain/UserMain.tsx, frontend/src/pages/UserReservation/UserReservation.tsx, frontend/src/types/common.ts, frontend/src/types/response.ts, frontend/src/types/styled.d.ts
- 예약자 메인 페이지 기능 구현
- 공간 선택 시 예약 현황을 조회할 수 있다
- 공간 선택 후 [예약] 버튼을 누르면 예약 페이지로 이동한다.
- 공간 목록을 불러오는 `useSpaces` 커스텀 훅 구현
- 추후 지도상의 모든 공간을 조회할 수 있는 API가 구현되었을 때 적용 요망
- `useInput` 커스텀 훅이 제너릭이 아닌 string 타입의 값만 받도록 수정함
- `onChange` 메소드의 `event.target.value`가 항상 string 타입이기 때문에 `onChange`로 값이 변경될 때 실제 값이 항상 string인 문제가 있어 `value`를 항상 string으로 받도록 강제하였습니다.
- 특정 확대 비율 및 특정 기기에서 `Panel.Header` 컴포넌트 내부가 꽉 차지 않는 문제가 있습니다. 추후 수정이 필요합니다.
- 예약 현황 수정 및 삭제 기능 및 UI는 구현되지 않았으니, 별도의 이슈와 PR에서 구현해야 합니다.
- #23
- #24
Close #146
=> feat: 예약자 메인 페이지 기능 구현 및 예약 현황 조회 API 연동

frontend/src/pages/UserMain/UserMain.tsx
- 예약 후 메인 페이지의 날짜를 변경해도 예약 목록을 올바르게 조회하지 못하는 문제를 수정합니다.
Close #153
=> fix: 예약 후 메인 페이지의 날짜가 올바르게 변경되지 않는 문제 수정

backend/src/main/java/com/woowacourse/zzimkkong/exception/authorization/AuthorizationHeaderUninvolvedException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/authorization/InvalidTokenException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/authorization/TokenExpiredException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/map/NoSuchMapException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/member/NoSuchMemberException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/reservation/NoSuchReservationException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/space/NoSuchSpaceException.java
-  Authorized exception 3개의 예외에 대해 메시지 모두 `로그인이 필요한 서비스입니다.` 로 통일했습니다.
-  NoSuch exception 예외메시지 모두 `존재하지 않는 ~ 입니다.` 로 통일했습니다.
Close #155
=> feat: 예외메시지 통일

frontend/src/App.tsx
- #186 의 문제를 해결합니다.
- 라우트 주소가 겹치도록 구현하는 경우 꼭 `exact` 속성을 추가해주세요!
- 혹은 무조건 `exact` 속성을 추가하는 것도 괜찮다고 생각합니다. 이 부분은 논의 후 적용하는 것도 좋아보입니다.
Close #186
=> fix: `/`를 제외한 페이지가 보여지지 않는 문제 수정

backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationPasswordAuthenticationRequest.java
- 비밀번호를 4자리 숫자로 입력하지 않는 경우 "비밀번호는 숫자 4자리만 입력 가능합니다."를 출력한다.
Close #197
=> refactor: 잘못된 비밀번호 입력 시 출력되는 예외 메시지를 수정한다.

frontend/src/components/Button/Button.styles.ts, frontend/src/components/Header/Header.styles.ts, frontend/src/components/Header/Header.tsx, frontend/src/components/Input/Input.styles.ts, frontend/src/pages/Join/Join.styles.ts, frontend/src/pages/Join/Join.tsx, frontend/src/pages/Login/Login.styles.ts, frontend/src/pages/Login/Login.tsx, frontend/src/types/response.ts
- 중간에 나오는 메시지 영역의 공간을 미리 확보하지 않고 메시지 길이에 맞춰서 보이도록 구현되었기 때문에, 메시지가 길 경우 버튼이 아래로 내려가는 문제가 있습니다. 이 정도 UI도 나쁘지는 않다고 생각하는데, 다른 크루들의 생각도 듣고 싶습니다.
- 메시지의 텍스트 크기도 좀 크다는 인상이 강하네요.
- figma 상의 `Input` 컴포넌트 색상은 #999999인데, 이미 팔레트가 GRAY가 정의되어 있으므로 이를 그대로 이용하여 `GRAY[500]` 색상으로 스타일링했습니다.
Close #209
=> refactor: 로그인/회원가입 페이지 UI 변경

frontend/webpack.config.js
Co-authored-by: JO YUN HO <yujo.dev@gmail.com>
Co-authored-by: Shim MunSeong <puterism.k@gmail.com>
Close #235
=> fix: depth가 2 이상인 url로 접속 시 manifest, bundle.js를 찾지 못하는 문제

backend/src/docs/asciidoc/map.adoc
- 누락되어 있던 맵 삭제 api에 대한 restDocs를 추가했습니다.
Close #273
=> docs: 맵 삭제 API에 대한 restDocs 추가

backend/src/main/java/com/woowacourse/zzimkkong/domain/Space.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/reservation/ConflictSpaceSettingException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/reservation/ReservationException.java, backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java, backend/src/test/java/com/woowacourse/zzimkkong/CommonFixture.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/ManagerReservationControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/SpaceControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/domain/SpaceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/GuestReservationServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/ManagerReservationServiceTest.java
-  space에 따른 setting이 설정됨에 따라 예약된 시간이 가능한 시간인지 확인합니다.
availableStartTime, availableEndTime에 따른 검증을 진행합니다.
- 예약 추가와 수정 시 모두 검증하도록 구현했습니다.
- 공간관리자와 예약자 모두 검증하도록 상위클래스인 ReservationService에 구현했습니다.
- 검증로직에 대한 도메인 테스트와 서비스테스트를 작성했습니다.
- 추가된 api가 없으므로 ControllerTest는 작성하지 않았습니다.
- 공간 예약조건과 관련해서 다양한 예약조건 검증 시 활용할 수 있도록 ReservationException을 상속하는 `ConflictSpaceSettingException`을 만들었습니다.
- 예약 가능한 시작시간과 끝시간 검증 테스트를 위해 테스트 Fixture의 BE 예약가능 시간을 10~22시로 수정했습니다.
Close #241
=> feat: 예약이 예약 가능 시간대에 예약되었는지 검증한다.

frontend/src/components/Header/Header.styles.ts, frontend/src/components/Header/Header.tsx
- Header 컴포넌트의 로고 선택 시 메인화면으로 이동
- 주소에 `:publicMapId`가 존재한다면 '/guest/:publicMapId'로 이동
- 아니라면 '/'로 이동
Close #341
=> feat: Header 로고 선택 시 메인 화면으로 이동

frontend/src/constants/routes.tsx
- `PUBLIC_ROUTE`, `PRIVATE_ROUTE` 에 `/map/create` 가 중복되어 들어가 있어 제거했습니다.
Close #384
=> refactor: 중복되는 라우터 제거

frontend/src/api/guestSpace.ts, frontend/src/hooks/useGuestReservations.ts, frontend/src/hooks/useGuestSpaces.ts, frontend/src/pages/GuestMap/GuestMap.tsx
- 예약자 메인 페이지에서 공간 관리자의 API가 호출되고 있던 문제 수정
- 파일 네이밍 컨벤션에 맞추어 File rename함
- `useSpaces.ts` -> `useGuestSpaces.ts`
- `api/space.ts` -> `api/guestSpace.ts`
Close #394
=> fix: 예약자 메인 페이지에서 공간 관리자의 API가 호출되고 있던 문제 수정

frontend/package.json, frontend/src/api/api.ts, frontend/webpack.config.js
- `process.env`에 `DEPLOY_ENV`를 추가했습니다.
- DEPLOY_ENV : 배포 환경을 설정합니다. (개발용 배포 환경 : `development` / 라이브 배포 환경 : `production`)
- 기존의 NODE_ENV는 Webpack mode를 설정하는 용도입니다.
- 배포 환경이 개발용 배포 환경인 `dev.zzimkkong.com`과 라이브 배포 환경인 `zzimkkong.com`으로 나눠짐에 따라 API baseURL도 이에 맞추어 변경할 수 있도록 `DEPLOY_ENV`를 추가하였습니다.
- 이에 맞추어 package.json에 script도 추가해두었습니다.
- dev branch에서 젠킨스 빌드 시 `yarn build:dev`로 동작하도록 설정을 변경해두었습니다.
- 현재 PR에서 젠킨스 빌드 테스트 시 무조건 `yarn build`로 동작하는데, `dev` 브랜치로 머지하는 PR과 `main` 브랜치로 머지하는 PR이 구별되었으면 좋겠습니다. PR에서는 테스트만 하기 때문에 `yarn build`와 `yarn build:dev` 간에 큰 차이는 없습니다.
Close #470
=> chore: DEPLOY_ENV 추가

frontend/src/components/Panel/Panel.styles.ts, frontend/src/components/Panel/Panel.tsx, frontend/src/pages/GuestMap/GuestMap.tsx, frontend/src/pages/ManagerMain/ManagerMain.styles.ts, frontend/src/pages/ManagerMain/ManagerMain.tsx, frontend/src/types/common.ts
- 공간관리자 공간목록 정렬
- 색상으로 우선 정렬
- 공간 이름 오름차순/내림차순(기본값: 오름차순)
- 예약 페이지 맵의 선 요소 끝을 둥글게 변경
Close #468 
Close #474
=> feat: 공간목록 오름차순, 내림차순 정렬

backend/src/main/java/com/woowacourse/zzimkkong/controller/MemberController.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/member/PresetFindResponse.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/MemberControllerTest.java
- 프리셋 전체조회 시 preset 의 id 값 같이 반환하도록 응답에 추가했습니다.
Close #479
=> feat: 프리셋 전체조회 시 id값 같이 반환

frontend/src/hooks/useListenManagerMainState.ts, frontend/src/pages/ManagerMapCreate/ManagerMapCreate.tsx
- 맵 추가 페이지에서 메인으로 돌아왔을 때 예약 목록이 로드되지 않는 문제 수정
Close #492
=> fix: 맵 추가 페이지에서 메인으로 돌아왔을 때 예약 목록이 로드되지 않는 문제 수정

frontend/src/App.tsx, frontend/src/components/Header/Header.tsx, frontend/src/pages/ManagerMain/ManagerMain.tsx
- 아래 스크린샷을 보면 최초 로그인시 불러온 `maps`가 로그아웃 시 clear되지 않았고, 이에 따라 메인화면에 진입할 때 기존에 가지고 있는 맵 목록의 첫 번째 맵의 id를 `selectedMapId`로 설정하고 있었습니다.
- 새롭게 로그인 된 아이디에서는 해당 맵의 `reservation`에 대한 접근권한이 없었고, 그렇기 때문에 로그아웃 되면서 다시 메인 화면으로 돌아가는 증상을 확인할 수 있었습니다.
- `App.tsx` 파일을 보면 `QueryClientProvider`로 전체 `App`을 감쌀 때 `client={queryClient}`라는 옵션을 준 것을 확인할 수 있습니다.
```tsx
const queryClient = new QueryClient();
const App = (): JSX.Element => {
return (
<QueryClientProvider client={queryClient}>
// ... 생략
</QueryClientProvider>
);
};
```
- 해당 queryClient를 export하여 로그아웃 시 queryCache를 초기화하는 로직을 추가하였습니다.
```tsx
const handleLogout = () => {
setAccessToken('');
queryClient.clear();  // <--- 새로 추가된 로직
localStorage.removeItem(LOCAL_STORAGE_KEY.ACCESS_TOKEN);
history.push(PATH.MANAGER_LOGIN);
};
```
- history와 관련된 문제인줄 알고 열심히 …
=> fix: 로그아웃 후 다른 아이디로 로그인 시, 로그아웃 되던 오류

frontend/src/hooks/useInputs.ts
- 하나의 객체에서 `input` 요소의 value를 관리하는 `useInputs` 커스텀 훅 구현
- input value들을 관리할 객체의 interface를 정의하고 Generic으로 넣어주세요.
```ts
interface Form {
email: string;
password: string;
}
const [{ email, password }, onChangeForm] = useInputs<Form>({ email: '', password: '' });
```
Close #513
=> feat: `useInputs` 커스텀 훅 구현

frontend/src/api/presets.ts, frontend/src/components/Modal/Modal.tsx, frontend/src/components/Select/Select.styles.ts, frontend/src/components/Select/Select.tsx, frontend/src/constants/api.ts, frontend/src/constants/message.ts, frontend/src/constants/space.ts, frontend/src/hooks/usePreset.ts, frontend/src/pages/ManagerSpaceEdit/ManagerSpaceEdit.styles.ts, frontend/src/pages/ManagerSpaceEdit/ManagerSpaceEdit.tsx, frontend/src/types/common.ts, frontend/src/types/response.ts
- 공간 예약 조건 프리셋 기능 구현 (추가, 조회 및 설정, 삭제)
https://user-images.githubusercontent.com/2542730/131951761-a5fa0bdf-1113-475e-82f5-44b7e7a24157.mp4
- 프리셋 선택 후, 예약 조건을 수정하면 프리셋 선택이 자동으로 해제됩니다.
https://user-images.githubusercontent.com/2542730/131951768-3c03b14e-b0da-490f-ae8d-bc84eb82a126.mp4
- 공간 편집 페이지에서 영역 드래그 시 커서가 선에 닿았을 때 올바르게 동작하지 않는 문제 수정
- 상수화되지 않은 alert message 상수화
- `Select` 컴포넌트에 `title` prop 추가
- 로컬에서 한번 사용해보시면서 기능 동작을 한 번 확인 부탁드리고 이와 관련된 피드백도 부탁드립니다!
Close #179 
Close #181 
Close #515
=> feat: 공간 예약 조건 프리셋 기능 구현

backend/src/main/java/com/woowacourse/zzimkkong/DataLoader.java, backend/src/main/java/com/woowacourse/zzimkkong/infrastructure/oauth/GithubRequester.java, backend/src/main/resources/application-dev.properties, backend/src/main/resources/application-local.properties, backend/src/main/resources/application-test.properties, backend/src/test/java/com/woowacourse/zzimkkong/infrastructure/oauth/GithubRequesterTest.java
- google은 redirect uri가 환경마다 달라야 해서 발생하는 문제였고, application-local과 application-prod에 수정하면서 해결했습니다.
- github은 제 생각엔 프론트에 client id가 잘못 전달된 것 같고, 500은 안터지게 예외 처리 로직을 추가했습니다.
- 두개 다 포스트맨 확인을 마쳤으니 이제 잘 것이라 추정하는 바입니다.
동작 확인하고 이슈 닫겠슴니다...
Close
=> fix: oauth 버그를 해결한다.

frontend/.gitignore, frontend/package.json, frontend/src/PrivateRoute.tsx, frontend/src/api/join.ts, frontend/src/api/login.ts, frontend/src/components/Input/Input.styles.ts, frontend/src/components/SocialAuthButton/SociaLoginButton.stories.tsx, frontend/src/components/SocialAuthButton/SocialAuthButton.styles.ts, frontend/src/components/SocialAuthButton/SocialJoinButton.stories.tsx, frontend/src/components/SocialAuthButton/SocialJoinButton.tsx, frontend/src/components/SocialAuthButton/SocialLoginButton.tsx, frontend/src/constants/path.ts, frontend/src/constants/routes.tsx, frontend/src/hooks/query/useGithubLogin.ts, frontend/src/hooks/query/useGoogleLogin.ts, frontend/src/hooks/useQueryString.ts, frontend/src/pages/ManagerLogin/ManagerLogin.tsx, frontend/src/pages/ManagerSocialJoin/ManagerSocialJoin.styles.ts, frontend/src/pages/ManagerSocialJoin/ManagerSocialJoin.tsx, frontend/src/pages/ManagerSocialJoin/units/SocialJoinForm.styles.ts, frontend/src/pages/ManagerSocialJoin/units/SocialJoinForm.tsx, frontend/src/pages/OAuthRedirect/GithubOAuthRedirect.tsx, frontend/src/pages/OAuthRedirect/GoogleOAuthRedirect.tsx, frontend/src/types/response.ts, frontend/webpack.config.js, frontend/yarn.lock
- Github, Google OAuth 공간 관리자 로그인 구현
- `SocialJoinButton` 컴포넌트 구현 (`Github로 시작하기`, `Google로 시작하기` 버튼)
- `Input` 컴포넌트에 disabled 스타일 적용
- `.env` 파일 및 설정 추가
- `PrivateRoute`에서 `token`을 Recoil이 아닌 `localStorage`에서 가져오도록 수정
- OAuth 로그인 시, Recoil에서 `token` 값이 바로 반영되지 않는 문제가 있어 `localStorage`에서 `token`을 가져오도록 수정 구현했습니다.
- 이메일 중복 체크, 공간 관리자 로그인 API URL을 올바르게 수정했습니다.
- 처음 로그인했을 때, 회원가입 이후 한 번 더 로그인을 시도해야 로그인됩니다. 이후, 소셜 회원가입하고 바로 로그인되어 메인 페이지로 넘어가도록 구현할 예정입니다.
- 공유드린 `.env` 파일을 root에 놓아주세요.
- `dotenv-webpack` 플러그인을 추가했으니 `yarn install`을 한 번 실행해주세요.
- PR 머지 후 실제로 잘 동작하는지 확인이 필요합니다. PR 머지하고 소셜 로그인 시도 후 문제가 생긴다면 바로 이슈 올리겠습니다.
Close #465
=> feat: Github, Google OAuth 공간 관리자 로그인 기능 구현

frontend/src/api/join.ts, frontend/src/api/login.ts
- OAuth 로그인 시 요청 URL이 잘못되어 있는 문제를 수정했습니다.
- URL 주소에 /api이라는 문자열이 두 번 포함되어 있는 상태였으며, 한 번만 포함되도록 수정했습니다.
Close #569
=> fix: OAuth 로그인 시 요청 URL이 잘못되어 있는 문제

backend/build.gradle, backend/src/test/java/com/woowacourse/zzimkkong/infrastructure/thumbnail/S3ProxyUploaderTest.java
- jacoco, sonarqube가 더이상 동작하지 않도록 제거했습니다.
- s3 쪽 테스트가 fail하길래 disabled 처리해두었습니다.
- 어차피 빌드는 테스트가 터지면 실패하니, 특별히 커버리지를 낮춰야하는 이유가 없다면 jacoco 정도는 살려도 되지 않을까? 라는 개인적인 생각이 있습니다.
- sonarqube는 사실상 major한 문제 관찰용이었으니 없어도 되겠지만 이거도 서버 안띄우고 돌릴 수는 있을 것 같습니다. 그치만 더이상 comment가 달리지 않으니 필요가 없다는 생각입니다.
Close #759
=> refactor: jacoco, sonarqube 관련 설정 제거

frontend/src/__mocks__/mockData.ts, frontend/src/api/managerMap.ts, frontend/src/api/managerSpace.ts, frontend/src/components/MapListItem/MapListItem.stories.tsx, frontend/src/components/MapListItem/MapListItem.styles.ts, frontend/src/components/MapListItem/MapListItem.tsx, frontend/src/pages/ManagerMain/units/MapDrawer.tsx, frontend/src/pages/ManagerMapEditor/ManagerMapEditor.tsx, frontend/src/pages/ManagerSpaceEditor/units/Form.tsx, frontend/src/types/common.ts
- API 명세가 변경 됨에 따라 type명 변경이 있었습니다.
- `mapImageSvg` ->  `thumbnail`
- `Drawer` -> `MapListItem` 컴포넌트에서 `dangerouslySetInnerHTML`을 사용 했습니다. 
- 체프와 썬의 아이디어를 반영해보려 했으나 시간 관계상 이번 PR에는 적용하기 힘들거 같습니다ㅠㅠ 추후 리팩토링 진행하도록 하겠습니다 
- 이 부분이 마음에 걸리는데 혹시 안전하게 처리할 수 있는 방법이 있다면 코멘트로 남겨주심 감사하겠습니다
Close #763
=> refactor: 관리자 메인 페이지에서 썸네일을 png대신 svg로 보여주도록 수정

backend/src/main/java/com/woowacourse/zzimkkong/controller/ControllerAdvice.java
- 그놈의 malicious String 때문에 DEV, PROD 가리지 않고 잉잉 우는 사이렌을 잠재우기 위해 해당 예외 잡아서 400으로 내리는 핸들링 코드를 추가했습니다.
- 자세한 내용은 [블로그](https://xrabcde.github.io/requestrejectedexception)에 정리했으니 참고하세요 '-'
Close #786
=> fix: RequestRejectedException 핸들링 코드 추가

frontend/src/utils/datetime.ts
- 예약 form 제출 시 입력받은 시간을 `formatTime`을 이용하여 Date타입으로 변환합니다.
- `formatTime`에서 입력받은 시간이 오후인 경우 시간에 12를 더하고 있었습니다.
- 오후 12시 30분의 경우 24시 30분이 되면서 유효하지 않은 시간으로 변환되어 모든 값을 입력하라는 오류가 나타났습니다.
- 오전 12시 30분의 경우 오후 12시 30분으로 변환되면서 의도치 않은 오류가 발생했습니다.
- (요약) 오전 12시는 00시가 아닌 12시, 오후 12시는 12시가 아닌 24시로 변환되어 오류남
- 입력받은 시간이 12인 경우, 오전이면 '00' 오후면 '12'로 시간을 반환하도록 변경
Close #791
=> fix: 예약 시간이 12시인 경우 예약을 완료할 수 없는 문제

frontend/package.json, frontend/src/App.tsx, frontend/src/api/guestReservation.ts, frontend/src/api/managerReservation.ts, frontend/src/components/DateInput/DateInput.stories.tsx, frontend/src/components/DateInput/DateInput.tsx, frontend/src/components/ReservationListItem/ReservationListItem.tsx, frontend/src/constants/date.ts, frontend/src/hooks/useTimePicker.ts, frontend/src/pages/GuestMap/GuestMap.tsx, frontend/src/pages/GuestMap/units/ReservationDrawer.tsx, frontend/src/pages/GuestReservation/GuestReservation.tsx, frontend/src/pages/GuestReservation/GuestReservationSuccess.tsx, frontend/src/pages/GuestReservation/units/GuestReservationForm.tsx, frontend/src/pages/ManagerMain/ManagerMain.tsx, frontend/src/pages/ManagerReservation/ManagerReservation.tsx, frontend/src/pages/ManagerReservation/units/ManagerReservationForm.tsx, frontend/src/utils/datetime.ts, frontend/yarn.lock
- 타임존 문제 해결을 위한 API 변경에 따른 date 관련 데이터 요청 타입 변경
- Dayjs 라이브러리 설치 및 설정
- 기존 시간 관련 함수에 Dayjs 타입도 처리할 수 있도록 수정 구현
- Dayjs를 이용하여 타임존이 Asia/Seoul로 고정되어 보이도록 수정
- 변경 사항이 좀 있는 PR입니다. 컴퓨터의 시간대를 변경해서 예약이 잘 수행되는지, 시간대가 UTC+09:00가 적용되어서 잘 출력되는지 이것저것 테스트해보신 후 리뷰 부탁드립니다.
- 날짜/시간 출력에 한정하여 Dayjs를 사용하면서 적용을 최소화하려고 해봤습니다.
- 기존 시간 관련 유틸 함수의 Date 객체 호환성을 유지하면서 동작하도록 구현했습니다. (e.g. `formatTime()`)
Close #745
=> refactor: 타임존 관리 방식 변경으로 인한 API 대응 및 타임존 고정

frontend/src/pages/ManagerMapEditor/ManagerMapEditor.tsx, frontend/src/pages/ManagerSpaceEditor/units/Form.tsx
=> feat: 맵 이름과 공간 이름의 최대길이를 20자로 제한한다

frontend/src/pages/ManagerMain/ManagerMain.tsx
- 선택된 맵 ID가 없을 때도 등록된 슬랙 웹훅 URL을 불필요하게 불러오는 문제를 수정합니다.
Close #810
=> fix: 선택된 맵 ID가 없을 때도 등록된 슬랙 웹훅 URL을 불러오는 문제 수정

backend/src/docs/asciidoc/map.adoc, backend/src/main/java/com/woowacourse/zzimkkong/controller/MapController.java, backend/src/main/java/com/woowacourse/zzimkkong/domain/Map.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/map/MapFindResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/map/NoticeCreateRequest.java, backend/src/main/java/com/woowacourse/zzimkkong/service/MapService.java, backend/src/main/resources/db/migration/prod/V15__map_add_column_notice.sql, backend/src/test/java/com/woowacourse/zzimkkong/controller/MapControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/dto/NoticeCreateRequestTest.java
- 공지사항 추가 api + map 테이블 notice 칼럼 추가
- 맵 조회시 공지사항, 슬랙url 필드 추가
Close #811 #818
=> feat: 맵별 공지사항 보여주는 기능 추가

backend/src/main/java/com/woowacourse/zzimkkong/dto/ValidatorMessage.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/map/NoticeCreateRequest.java, backend/src/test/java/com/woowacourse/zzimkkong/dto/NoticeCreateRequestTest.java
- 공지사항 글자수초과 시 나오는 메시지가 예약내용에 사용하던 애로 나오고 있어서 공지사항 관련 메시지 추가 후 수정했습니다.
Close #827
=> fix: 공지사항 글자수초과 예외메시지 수정

backend/src/main/java/com/woowacourse/zzimkkong/dto/slack/SlackResponse.java
- 슬랙 예약알림 메시지에 교육장 정보도 같이 보여지도록 추가했습니다.
- `장소 : 잠실 캠퍼스`
- ~~일단은 우테코에서만 슬랙알림을 쓰고 있어서 필드이름을 `교육장명`이라고 하긴 했는데 범용적으로 사용되길 원하시면 맵이름... 뭐 그런걸로 바꿔야 하긴 합니다. 이부분은 의견 주세요1!~~
=> **`장소` 로 결정!**
- 귀찮을 줄 알고 계속 미뤘는데 해보니까 생각보다 수정할 게.. 없네요...? 그냥 머지하면 될듯.... 
Close #798
=> feat: 슬랙예약알림 메시지에 교육장 정보 추가

frontend/src/api/join.ts, frontend/src/api/login.ts
- 회원 관련 API의 URL이 `/managers`에서 `/members`로 변경됨에 따라 변경된 URL로 API 요청을 보내도록 수정했습니다.
=> refactor: 회원 관련 API의 URL을 `/managers`에서 `/members`로 변경

frontend/src/api/join.ts, frontend/src/constants/manager.ts, frontend/src/constants/message.ts, frontend/src/constants/regexp.ts, frontend/src/constants/throwError.ts, frontend/src/hooks/query/useEmojiList.ts, frontend/src/pages/ManagerJoin/ManagerJoin.tsx, frontend/src/pages/ManagerJoin/units/EmojiSelector.styles.ts, frontend/src/pages/ManagerJoin/units/EmojiSelector.tsx, frontend/src/pages/ManagerJoin/units/JoinForm.styles.ts, frontend/src/pages/ManagerJoin/units/JoinForm.tsx, frontend/src/pages/ManagerSocialJoin/ManagerSocialJoin.tsx, frontend/src/pages/ManagerSocialJoin/units/SocialJoinForm.styles.ts, frontend/src/pages/ManagerSocialJoin/units/SocialJoinForm.tsx, frontend/src/types/common.ts, frontend/src/types/response.ts
- 회원가입 시 유저명과 프로필 이모지를 입력받도록 폼 수정
- 유저명 입력 후, blur 시 이름 중복을 확인하는 API를 요청합니다.
- OAuth로 회원가입 시 유저명과 프로필 이모지를 입력받도록 폼 수정
- 로컬 환경에서는 소셜 회원가입 화면을 확인할 수 없어 dev 환경에 배포 이후 동작을 확인해야 합니다. 이에 따라 추가 수정을 위한 PR을 올릴 수 있습니다.
Close #879
=> feat: 회원가입 시 유저명과 프로필 이모지를 입력받도록 폼 수정

frontend/src/__mocks__/mockData.ts, frontend/src/api/api.ts, frontend/src/api/guestReservation.ts, frontend/src/components/ManagerReservationListItem/ManagerReservationListItem.stories.tsx, frontend/src/constants/message.ts, frontend/src/pages/GuestMap/GuestMap.tsx, frontend/src/pages/GuestMap/units/LoginPopup.tsx, frontend/src/pages/GuestMap/units/PasswordInputModal.tsx, frontend/src/pages/GuestMap/units/ReservationDrawer.tsx, frontend/src/pages/GuestReservation/GuestReservation.tsx, frontend/src/pages/GuestReservation/units/MemberGuestReservationForm.tsx, frontend/src/types/common.ts
- 로그인한 상태에서 예약을 추가/수정하는 기능 구현
- 로그인한 상태에서 예약을 삭제하는 기능 구현
Close #868
=> feat: 로그인한 상태에서 예약을 추가/수정하는 기능 구현

frontend/src/components/Switch/Switch.styled.ts, frontend/src/constants/routes.tsx, frontend/src/hooks/useTimePicker.ts, frontend/src/pages/GuestMap/GuestMap.styles.ts, frontend/src/pages/GuestMap/GuestMap.tsx, frontend/src/pages/GuestMap/GuestMapContainer.tsx, frontend/src/pages/GuestMap/providers/GuestMapFormProvider.tsx, frontend/src/pages/GuestMap/units/Aside.tsx, frontend/src/pages/GuestMap/units/GuestMapDrawing.styles.ts, frontend/src/pages/GuestMap/units/GuestMapDrawing.tsx, frontend/src/pages/GuestMap/units/ReservationForm.styled.ts, frontend/src/pages/GuestMap/units/ReservationForm.tsx
=> feat: 예약 가능 시간에 따라 맵에서 공간을 활성화/비활성화로 보이게 하는 기능 구현

backend/src/docs/asciidoc/space.adoc, backend/src/main/java/com/woowacourse/zzimkkong/controller/GuestSpaceController.java, backend/src/main/java/com/woowacourse/zzimkkong/domain/Settings.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationCreateUpdateRequest.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/space/SpaceFindAllAvailabilityResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/space/SpaceFindAvailabilityResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/infrastructure/datetime/TimeZoneUtils.java, backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java, backend/src/main/java/com/woowacourse/zzimkkong/service/SpaceService.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/GuestReservationControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/GuestSpaceControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/ManagerReservationControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/repository/ReservationRepositoryImplTest.java, backend/src/test/java/com/woowacourse/zzimkkong/repository/ReservationRepositoryTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/AdminServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/GuestReservationServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/ManagerReservationServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/SpaceServiceTest.java
- 특정 datetime slot (start ~ end) 이 주어질 때, 전체 공간의 사용 가능 여부를 조회하는 API 추가
- FE 작업을 위해서 DEV 선 배포 하겠습니다 @yujo11 @Puterism @SunYoungKwon 
- API docs: https://api.zzimkkong.com/docs/index.html#_%EA%B3%B5%EA%B0%84_%EC%A0%84%EC%B2%B4_%EC%82%AC%EC%9A%A9_%EA%B0%80%EB%8A%A5_%EC%97%AC%EB%B6%80_%EC%A1%B0%ED%9A%8C
- 개발 하면서 추가, 수정 되어야할 부분 바로바로 알려주세요~
Close #888
=> feat: 특정 맵 > 전체 공간에 대한 사용가능여부 조회 API 추가

backend/src/docs/asciidoc/reservation.adoc, backend/src/main/java/com/woowacourse/zzimkkong/controller/GuestReservationController.java, backend/src/main/java/com/woowacourse/zzimkkong/domain/Reservation.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationCreateUpdateRequest.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/reservation/ReservationOwnerResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/infrastructure/datetime/TimeZoneUtils.java, backend/src/main/java/com/woowacourse/zzimkkong/repository/ReservationRepository.java, backend/src/main/java/com/woowacourse/zzimkkong/service/ReservationService.java, backend/src/main/resources/db/migration/prod/V19__add_non_null_member_data.sql, backend/src/main/resources/db/migration/prod/V21__non_login_reservation.sql, backend/src/test/java/com/woowacourse/zzimkkong/Constants.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/GuestReservationControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/ManagerReservationControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/repository/ReservationRepositoryImplTest.java, backend/src/test/java/com/woowacourse/zzimkkong/repository/ReservationRepositoryTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/AdminServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/GuestReservationServiceTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/ManagerReservationServiceTest.java
- username을 입력받으면 해당 username에 exact match 하는 예약내역을 조회한다
- searchStartTime 을 request param으로 받아 이를 기준으로 pagination 처리
- #892 이슈 얹어서 처리 (페이지 네이션 쿼리에서 예약 시간 컷 다 끝내야함)
Close #889 #892
=> feat: 비회원 예약 조회 API 추가

frontend/src/components/Header/Header.tsx, frontend/src/pages/GuestMap/units/LoginPopup.tsx, frontend/src/pages/GuestMap/units/ReservationList.styled.ts, frontend/src/pages/GuestMap/units/ReservationList.tsx, frontend/src/pages/GuestNonLoginReservationSearch/GuestNonLoginReservationSearch.tsx, frontend/src/pages/Login/Login.tsx
=> feat: 헤더에 비회원 예약조회 링크 추가

backend/src/main/java/com/woowacourse/zzimkkong/controller/MemberController.java, backend/src/main/java/com/woowacourse/zzimkkong/domain/Member.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/member/ChangePasswordRequest.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/member/ConfirmationNewPasswordMismatchException.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/member/PasswordMismatchException.java, backend/src/main/java/com/woowacourse/zzimkkong/service/MemberService.java, backend/src/test/java/com/woowacourse/zzimkkong/controller/MemberControllerTest.java, backend/src/test/java/com/woowacourse/zzimkkong/dto/ChangePasswordRequestTest.java, backend/src/test/java/com/woowacourse/zzimkkong/service/MemberServiceTest.java
- 비밀번호 변경 기능을 추가합니다.
- 기존의 비밀번호와 새 비밀번호를 두 번 입력해오면 이에 대해 검증하고 비밀번호를 변경합니다.
백에서 검증은 해주지만, 프론트에서도 새 비밀번호 확인란 비교해서 애초에 걸러주는 로직이 있으면 좋겠네용
Close #909
=> feat: 비밀번호 변경 기능

backend/src/main/java/com/woowacourse/zzimkkong/service/MemberService.java, backend/src/test/java/com/woowacourse/zzimkkong/service/MemberServiceTest.java
- 자신의 닉네임은 중복검사에서 제외합니다.
Close #913
=> feat: 회원 정보 수정에서 회원 스스로의 닉네임은 중복검사에서 제외하는 분기 생성

frontend/src/components/Input/Input.styles.ts
- iOS에서 로그인 후 예약 시 이름 필드 흐리게 보이는 현상 해결
[Before]
[After]
Close #907
=> fix: iOS에서 로그인 후 예약 시 이름 필드 흐리게 보이는 현상 해결

frontend/src/api/member.ts, frontend/src/constants/path.ts, frontend/src/constants/routes.tsx, frontend/src/pages/ManagerPasswordEdit/ManagerPasswordEdit.styles.ts, frontend/src/pages/ManagerPasswordEdit/ManagerPasswordEdit.tsx, frontend/src/pages/ManagerProfileEdit/ManagerProfileEdit.tsx, frontend/src/pages/ManagerProfileEdit/units/ProfileEditForm.styles.ts, frontend/src/pages/ManagerProfileEdit/units/ProfileEditForm.tsx
- 입력 전
- 입력 후
- 내 정보 수정 페이지
- 이전 비밀번호가 일치하지 않을 때
Close #915
=> feat: 로그인 유저의 비밀번호 변경  기능

backend/src/main/java/com/woowacourse/zzimkkong/dto/member/ChangePasswordRequest.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/member/PasswordMismatchException.java, backend/src/test/java/com/woowacourse/zzimkkong/dto/ChangePasswordRequestTest.java
- 비밀번호 변경 api에서 기존 비밀번호 오기입시 에러 메세지를 구체화 합니다.
- 비밀번호 변경 api에서 기존 비밀번호에 대해 패턴 검사를 실행하지 않습니다.
close #909
=> feat: 비밀번호 변경 api에서 기존 비밀번호 오기입시 에러 메세지 구체화, 기존 비밀번호에 대해 패턴 검사를 실시하지 않음, dto 패턴 테스트 코드 추가

frontend/src/api/member.ts, frontend/src/pages/ManagerProfileEdit/ManagerProfileEdit.tsx
- OAuth의 경우
- OAuth가 아닌 경우
Close #934
=> feat: OAuth 로그인일 경우 비밀번호 변경 텍스트, 링크가 보이지 않도록 하는 기능

backend/src/main/java/com/woowacourse/zzimkkong/controller/ControllerAdvice.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/ErrorResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/ValidatorMessage.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/authorization/TokenExpiredException.java, backend/src/main/java/com/woowacourse/zzimkkong/infrastructure/auth/JwtUtils.java
- 이슈 #948 #949 함께 해결
- ControllerAdvice 코드 수정 
- logging 시 발생한 exception 도 같이 찍도록 수정
- Error Response handler 별로 알맞게 수정
- internal server error 발생 시, 클라측에 나가는 메세지 (i.e. 사용자가 볼 메세지) 변경
- `일시적으로 접속이 원활하지 않습니다. 잠시 후 다시 이용해 주시기 바랍니다.`
- 기존에 ControllerAdvice에서 클라측에 나갈 메세지가 로그로 찍히는 부분이 있었음
- 우리가 클라측에 나갈만한 안내 메세지를 로그에서 봐서 도움 되는 부분이 없으므로 Exception의 메세지를 대신 찍도록 변경했습니다
Close #948 
#949 는 엄밀히 따지면 FE 의 버그 사항이므로 Close 하지 않습니다
=> feat: ControllerAdvice 개편

frontend/src/pages/GuestNonLoginReservationSearch/units/GuestNonLoginReservationSearchResult.tsx
- 비회원 예약 조회 > 예약 수정 아이콘 클릭 > 예약 수정 페이지로 이동 하도록 수정
- commit 4abc424b8c764a172fc4bdcd3d9b709730ca8547 영향
- 해당 커밋 내역보고 맞춰서 수정했습니다
Close #953
=> fix: 비회원 예약 조회 > 수정 버튼 클릭시 예약 수정 페이지로 정상적으로 넘어가도록 수정

backend/src/main/java/com/woowacourse/zzimkkong/config/logaspect/LogAspect.java, backend/src/main/java/com/woowacourse/zzimkkong/config/logaspect/LogTraceIdInterceptor.java, backend/src/main/java/com/woowacourse/zzimkkong/config/logaspect/RequestLoggingFilter.java, backend/src/main/java/com/woowacourse/zzimkkong/controller/ControllerAdvice.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/ErrorResponse.java, backend/src/main/java/com/woowacourse/zzimkkong/dto/ValidatorMessage.java, backend/src/main/java/com/woowacourse/zzimkkong/exception/authorization/TokenExpiredException.java, backend/src/main/java/com/woowacourse/zzimkkong/infrastructure/auth/JwtUtils.java, backend/src/main/resources/appenders/async-console-appender.xml, backend/src/main/resources/appenders/file-appender.xml, backend/src/main/resources/appenders/slack-appender.xml, backend/src/main/resources/application-dev.properties, backend/src/main/resources/logback-spring.xml, frontend/src/pages/GuestNonLoginReservationSearch/units/GuestNonLoginReservationSearchResult.tsx
- server log 개편 #945 #950
- 비회원 예약 조회 > 예약 수정 화면 안넘어 가지는 이슈 수정 #954
=> release: v2.1.1
